#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: before 2016-12-01
# Purpose: Performs virus scan of system (with exclusions) and writes 
# results to LOG file. Runs in cron: ~$ sudo crontab -l to see schedule.
#
#------------------------------------------------------------------------------
# Change Log
# 2019-03-10: removed sudo; script runs in sudo crontab
#------------------------------------------------------------------------------

home-scan () 
{
# Performs virus scan of $HOME and writes results to LOG file.
    {
    printf '%s\n' "Scan started: $(date +%F_%T)"
    clamscan -ir /home/woods/
    printf '\n%s\n'  "Scan completed: $(date +%F_%T)"
    } >> "$LOG" 2> /dev/null
return 0
}

root-scan () 
{
# Performs virus scan of / (with exclusions) and writes results to LOG file.
    {
    printf '%s\n\n' "Scan started: $(date +%F_%T)"
    tail /var/log/clamav/freshclam.log
    clamscan -ir / --exclude-dir='^/(cdrom|dev|media|mnt|proc|snap|srv|sys)'
    printf '\n%s\n'  "Scan completed: $(date +%F_%T)"
    } >> "$LOG" 2> /dev/null
return 0
}

dow=$(date +%w)
if [[ "$dow" = 0 ]]
then
    LOG=/home/woods/clamscan/_av-scan-weekly_$(date +%F_%T)
    root-scan
else
    LOG=/home/woods/_av-scan-daily.txt
    rm -f "$LOG"
    home-scan
fi
chown woods:woods "$LOG"

