#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: before 2016-12-01
# Purpose: Performs virus scan of system (with exclusions) and writes 
# results to LOG file. Runs in cron: ~$ sudo crontab -l to see schedule.
#
#------------------------------------------------------------------------------
# Change Log
# 2019-04-10: Updated scan report format. 
#------------------------------------------------------------------------------

home-scan () 
{
# Performs virus scan of $HOME and writes results to LOG file.
    {
    tail /var/log/clamav/freshclam.log
    printf '\n\n%s\n' "Scan started: $(date +%F_%T)"
    clamscan -ir /home/woods/
    printf '\n%s\n'  "Scan completed: $(date +%F_%T)"
    } >> "$LOG" 2> /dev/null
return 0
}

root-scan () 
{
# Performs virus scan of / (with exclusions) and writes results to LOG file.
    {
    tail /var/log/clamav/freshclam.log
    printf '\n\n%s\n' "Scan started: $(date +%F_%T)"
    clamscan -ir --exclude-dir='^/(cdrom|dev|home|media|mnt|proc|snap|srv|sys)' /
    printf '\n%s\n'  "Scan completed: $(date +%F_%T)"
    } >> "$LOG" 2> /dev/null
return 0
}

dow=$(date +%w)
if [[ "$dow" = 0 ]]
then
    LOG=/home/woods/clamscan/_$(date +%F_%T)_avscan-root.txt
    root-scan
else
    LOG=/home/woods/_avscan-home.txt
    [[ -e "$LOG" ]] && rm -f "$LOG"
    home-scan
fi
chown woods:woods "$LOG"
