#! /usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2016-05-20
# Purpose: Reports home directory files that need to be synch'd. Runs in cron
# to create an hourly report based on the following one-liner:
#

#------------------------------------------------------------------------------
# Change Log
# 2020-05-04: Updated target.
#------------------------------------------------------------------------------

exclude_list=/home/woods/xlists/x-homesync
source=/home/woods/
target=/media/woods/Data/home_knix/
sim_log=/home/woods/_home-files-to-sync

echo "***** $(date -R) *****" > "$sim_log"

main () {

    {
    echo
    rsync -n -avhiOu --progress --stats --delete \
    --exclude-from="$exclude_list" "$source" "$target"
    } >> "$sim_log"

}

main
