#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: before 2016-07-07
# Purpose: Log smartctl status of system drives. Runs in cron daily.

#--------------------------------------------------------------------------------------
# Change Log
# 2025-02-09: Updates to include NvMe drives. Automated drive list in-work.
#--------------------------------------------------------------------------------------

LOG=/home/woods/SMART/$(date +%F_%H%M%S)_smart-status.txt

#drive_list=( $(sudo fdisk -l | awk '/\/dev\/sd.1/ {print $1}' | sort -u) )
#drive_list=( $(sudo blkid | grep -v loop | awk '/\/dev\/sd/ || /\/dev\/nvme/ {print $1}' | sort -u) )
#drive_list=( "$(lsblk -n -o name,type | grep -w disk | sort -u | awk '$1 ~ /^[a-z]/ {print $1}')" )
#drive_list=(/dev/sda /dev/sdb /dev/nvme0 /dev/nvme1)
drive_list=( $(sudo blkid | grep -v loop | awk '{if ($0 ~ /\/dev\/sd/) {print substr($0, 1, 9)} \
if ($0 ~ /\/dev\/nvme/) {print substr($0, 1, 10)} }' | sort -u) )
divider="-------------------------------------------------------------------------------------------------"

get_status () {
# Obtains smartctl drive info, health, attributes, error & selftest status then writes to LOG

    for drive in "${drive_list[@]}" ; do
        {
        printf '%s\n\n' "********** $drive SMART Status recorded: $(date) **********"
        sudo smartctl -i -HA -l error "$drive"
        printf '%s\n\n\n' "$divider" 
        } >> "$LOG" 2> /dev/null
    done
    
return 0
}

get_summary () {
# Creates a summary of critical SMART attributes organized by drive.

    smart_sum=/home/woods/smart_summary.txt
    
    if [ -e "$smart_sum" ]; then
        rm -f "$smart_sum"
    fi

    {
    awk '/\/dev\/sd|\/dev\/nvme|Model|Serial|PASSED|Reallocated|Pending|Uncorrectable|Hour|Cycle|Temp|Wear/ {print $0}
    /LBAs/ {printf "%s%69.2f%s\n", "Total_LBAs_Written:",$10*512/1024/1024/1024/1024, " TiB"}
    /Errors|Error Count:/ {printf "%s\n\n", $0}' "$LOG"
    } >> "$smart_sum"
    
    # colorize keywords in summary report
    # Source: https://unix.stackexchange.com/questions/45924/
    
    esc=$(printf '\033')
    sed -i -e "s/PASSED/${esc}[32m&${esc}[0m/" -e "s/No Errors Logged/${esc}[32m&${esc}[0m/" "$smart_sum"

return 0
}

main () {
# Calls functions that create smartcrl LOG and summary report.

    get_status
    get_summary
    sudo chown woods:woods "$LOG" "$smart_sum"
    
return 0
}

main

