#! /usr/bin/env bash

# Author: Woods Wannamaker
# Date: before 2016-05-22
# Purpose: rsync simulation of Data drive with mounted backup drives.
# Report log created in cron hourly.

#------------------------------------------------------------------------------
# Change Log
# 2019-05-02: Refactored. Updated rsync flags, variable names.
#------------------------------------------------------------------------------

# Definitions
source=/media/woods/Data/
exclude_list=/home/woods/xlists/x-datasync
sim_log=/home/woods/_data-files-to-sync
error1="***** Source Drive NOT Mounted! Program terminated with exit code: 1 *****"
error2="***** Exclusion list not found! Exiting...with error code: 2 *****"

if ! (mountpoint -q "$source")
then
    printf "\n%s\n\n" "$error1"
    exit 1
elif ! [[ -f "$exclude_list" ]]
then
    printf "\n%s\n\n" "$error2"
    exit 2
else
    drive_list=( $(mount | awk '/\/media\/woods\/Data-/ {print $3}' | sort -u) )
    printf "%s\n\n" "***** $(date -R) *****" > "$sim_log"
fi

function sync_control () {
# Simulates & reports synchronization of source drive with target drive in drive_list.

    {
    
    for mount_point in "${drive_list[@]}"; do
    
        target=$mount_point/
        
        if ! (mountpoint -q "$source"); then
            printf "\n%s\n\n" "$error1"
            exit 1
        elif ! (mountpoint -q "$target"); then
            printf "\n\n%s\n\n" "***** $target Excluded. Drive NOT Mounted! *****"
        else
        ############################# RSYNC BLOCK #############################
        
            printf "%s\n\n" "Data drive files to sync with $target"
            
            rsync -n -avhiOu --progress --stats --delete \
            --exclude-from="$exclude_list" "$source" "$target"
            
            printf "\n\n"
            
        ############################# RSYNC BLOCK #############################
        fi
        
    done
    
    } >> "$sim_log"
    
return 0
}

sync_control
