#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2016-05-20
# Purpose: Reports home directory files that need to be synch'd. Runs in cron
# to create an hourly report.

#------------------------------------------------------------------------------
# Change Log
# 2016-09-30: changed EXCLUDE_LIST source file name. 
# 2016-11-14: updated with fixes from shellcheck 
#------------------------------------------------------------------------------

EXCLUDE_LIST=/home/woods/rsync/xclude-list.homesync
SOURCE=/home/woods/
TARGET=/media/woods/Misc/home_sync/
LOG=/home/woods/rsync/_home-files-to-sync

echo "***** $(date -R) *****" > "$LOG"
echo >> "$LOG"

# rsync -n -rpgDvOult --progress --delete --modify-window=1 --exclude-from=/home/woods/rsync/xclude-list.homesync /home/woods/ /media/woods/Misc/home_sync/ | egrep -v '/$'

rsync -n -rpgDvOult --progress --delete --modify-window=1 --exclude-from=$EXCLUDE_LIST "$SOURCE" "$TARGET" | egrep -v '/$' >> "$LOG"
