#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2018-08-30
# Purpose: Performs background pings of Amazon Kindle Fire update sites. 
# Google is checked followed by FQDNs and list of AMZN IPv4 update addresses.

clear

kfcheck () {

    ip="$1"
    ( ping -c1 -W1 "$ip" > /dev/null 2>&1 && \
    printf '%-40s%s\n' "$ip" " not blocked" || \
    printf '%-40s%s\n' "$ip" " blocked" ) &
    wait
    
return 0
}

kfcheck 8.8.8.8
kfcheck google.com && echo


kfcheck a1896.g.akamai.net
kfcheck a1910.d.akamai.net
kfcheck amzdigital-a.akamaihd.net
kfcheck amzdigitaldownloads.edgesuite.net
kfcheck amzdigital-a.akamaihd.net.edgesuite.net
kfcheck softwareupdates.amazon.com
kfcheck updates.amazon.com
