#! /usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2018-01-23 
# Purpose: Performs background pings of network ip addresses. A quick test
# of WAN and LAN network status.
#
#------------------------------------------------------------------------------
# Change Log
# 2018-01-23: fork of ping_monet, modified based on the following article:
# https://www.shellscript.sh/tips/ping/
#------------------------------------------------------------------------------

clear

net_check () {
#Function: Performs 1 sec background ping in separate background processes
#then displays message if ip was reached.

for host in $2
do
  ip="$1.$host"
  (ping -c1 -w1 "$ip" > /dev/null 2>&1 && echo "$ip reached") &
done
wait
echo
    
return 0
}

net_check "10.0.0" "$(seq 1 254)" 
net_check "192.168.3" "$(seq 1 254)"
net_check "8.8.8" "8"

