#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2016-12-05
# Purpose: Performs background pings of network devices. 
#
#------------------------------------------------------------------------------
# Change Log
# 2019-09-12: removed failure reporting; added sequence for subnets 
#------------------------------------------------------------------------------

clear

ping_monet () {
# Function: Performs 1 sec background ping in separate background processes
# then displays message if ip was reached or failed. Checks DNS resolution.
# Source: https://www.shellscript.sh/tips/ping/

for host in $2
do
    ip="$1.$host"
    ( ping -c1 -W1 "$ip" > /dev/null 2>&1 && \
	    printf '%-16s%s\n' "$ip" "success" ) &
done
wait
    
return 0
}

ping_monet "8.8.8" "8"
ping_monet "google" "com" && echo
ping_monet "10.0.0" "1" && echo
ping_monet "192.168.3" "$(seq 1 254)" && echo
ping_monet "192.168.20" "$(seq 1 254)" && echo
ping_monet "192.168.30" "$(seq 1 254)" && echo
ping_monet "192.168.50" "$(seq 1 254)" && echo

