#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2016-09-26
# Purpose: Generates list of passwords
# Source: http://serverfault.com/questions/283294/how-to-read-in-n-random-characters-from-dev-urandom

clear

read -p "How many passwords to generate?: " number_pass
read -p "Enter password length: " pass_length
echo

printf '%s\n' "$(head -c 5000 /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | fold -w $pass_length | head -n $number_pass)"

echo

