#!/usr/bin/env bash

# Author: Woods Wannamaker
# Date: 2019-02-20
# Purpose: rsync unifi backups (*.unf) from unitylt controller to kdepc
# Source: Tom Lawrence (LTS_Tom)  https://forums.lawrencesystems.com/

push_update()
{
rsync -avrhiO --no-perms --delete --progress --stats \
/var/lib/unifi/backup/autobackup/ \
-e ssh woods@192.168.3.10:/media/woods/Data/unf_autobackups/
}

push_update
